### ISSUE TITLE
Stuck while exceution of setup with world.db

### ISSUE THREAD

**Issue by tschmidt01** [openmundi/world.db#17]
Running ```sportdb --dbname football.db setup --worldinclude world.db``` stucks after printing following to the console:

```
[...]
[Name.parse] adding Name record:
  {:place_id=>730, :place_kind=>"CITY", :name=>"Gujranwala"}
[Name.parse] adding Name record:
  {:place_id=>730, :place_kind=>"CITY", :name=>"Gujranwala"}
```

**Comment by geraldb** [comment]
Welcome to world.db. Please send build errors to the [mailing list/forum](https://groups.google.com/group/openmundi). Thanks for your understanding. Cheers..
