### ISSUE TITLE
Looking for opportunity to contribute

### ISSUE THREAD

**Issue by mamat-rahmat** [openmundi/world.db#18]
Hi, i'm looking for any opportunity to contribute to this project, especially for my country data (Indonesia). Is there anything like contribution guideline?

**Comment by geraldb** [comment]
@mamat-rahmat  You're more than welcome. I'd say the "best" way is to look at Austria (at-austria) or Germany (de-deutschland) and start with a country repo for Indonesia (on your github account). For contribution guidelines - see / use the country repos as examples. Cheers.

**Comment by geraldb** [comment]
@mamat-rahmat  Please use the [forum / mailing list](https://groups.google.com/group/openmundi) for future questions. Thanks. Cheers.
